config/routes.rb
Rails.application.routes.draw do
  resources :prefectures
  resources :cities
  resources :volunteers
  resources :prefectures

  get '/index' , to: 'top#index'
  root to: 'top#index'
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]

  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url, notice: 'Volunteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:city_id, :date, :time, :belongings, :note, :contact_id)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.haml
= form_for @volunteer do |f|
  - if @volunteer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@volunteer.errors.count, "error")} prohibited this volunteer from being saved:"
      %ul
        - @volunteer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :city_id
    = f.number_field :city_id
  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :belongings
    = f.text_area :belongings
  .field
    = f.label :note
    = f.text_area :note
  .field
    = f.label :contact_id
    = f.text_field :contact_id
  .actions
    = f.submit 'Save'

app/views/volunteers/edit.html.haml
%h1 Editing volunteer

= render 'form'

= link_to 'Show', @volunteer
\|
= link_to 'Back', volunteers_path

app/views/volunteers/index.html.haml
%h1 Listing volunteers

%table
  %thead
    %tr
      %th City
      %th Date
      %th Time
      %th Belongings
      %th Note
      %th Contact
      %th
      %th
      %th

  %tbody
    - @volunteers.each do |volunteer|
      %tr
        %td= volunteer.city_id
        %td= volunteer.date
        %td= volunteer.time
        %td= volunteer.belongings
        %td= volunteer.note
        %td= volunteer.contact_id
        %td= link_to 'Show', volunteer
        %td= link_to 'Edit', edit_volunteer_path(volunteer)
        %td= link_to 'Destroy', volunteer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Volunteer', new_volunteer_path

app/views/volunteers/new.html.haml
%h1 New volunteer

= render 'form'

= link_to 'Back', volunteers_path

app/views/volunteers/show.html.haml
%p#notice= notice

%p
  %b City:
  = @volunteer.city_id
%p
  %b Date:
  = @volunteer.date
%p
  %b Time:
  = @volunteer.time
%p
  %b Belongings:
  = @volunteer.belongings
%p
  %b Note:
  = @volunteer.note
%p
  %b Contact:
  = @volunteer.contact_id

= link_to 'Edit', edit_volunteer_path(@volunteer)
\|
= link_to 'Back', volunteers_path