config/routes.rb
Rails.application.routes.draw do
  resources :prefectures
  resources :cities
  resources :volunteers
  resources :prefectures

  get '/index' , to: 'top#index'
  root to: 'top#index'
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  before_action :set_prefecture, only: [:show, :edit, :update, :destroy]

  # GET /prefectures
  # GET /prefectures.json
  def index
    @prefectures = Prefecture.all
  end

  # GET /prefectures/1
  # GET /prefectures/1.json
  def show
  end

  # GET /prefectures/new
  def new
    @prefecture = Prefecture.new
  end

  # GET /prefectures/1/edit
  def edit
  end

  # POST /prefectures
  # POST /prefectures.json
  def create
    @prefecture = Prefecture.new(prefecture_params)

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully created.' }
        format.json { render :show, status: :created, location: @prefecture }
      else
        format.html { render :new }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefectures/1
  # PATCH/PUT /prefectures/1.json
  def update
    respond_to do |format|
      if @prefecture.update(prefecture_params)
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @prefecture }
      else
        format.html { render :edit }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1
  # DELETE /prefectures/1.json
  def destroy
    @prefecture.destroy
    respond_to do |format|
      format.html { redirect_to prefectures_url, notice: 'Prefecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefecture
      @prefecture = Prefecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prefecture_params
      params.require(:prefecture).permit(:name_ja, :name_hira, :name_en, :latitude, :longitude, :population, :url, :twitter, :tel, :wikipedia)
    end
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/prefectures/_form.html.haml
= form_for @prefecture do |f|
  - if @prefecture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@prefecture.errors.count, "error")} prohibited this prefecture from being saved:"
      %ul
        - @prefecture.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name_ja
    = f.text_field :name_ja
  .field
    = f.label :name_hira
    = f.text_field :name_hira
  .field
    = f.label :name_en
    = f.text_field :name_en
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :population
    = f.number_field :population
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :tel
    = f.text_field :tel
  .field
    = f.label :wikipedia
    = f.text_field :wikipedia
  .actions
    = f.submit 'Save'

app/views/prefectures/edit.html.haml
%h1 Editing prefecture

= render 'form'

= link_to 'Show', @prefecture
\|
= link_to 'Back', prefectures_path

app/views/prefectures/index.html.haml
%h1 Listing prefectures

%table
  %thead
    %tr
      %th Name ja
      %th Name hira
      %th Name en
      %th Latitude
      %th Longitude
      %th Population
      %th Url
      %th Twitter
      %th Tel
      %th Wikipedia
      %th
      %th
      %th

  %tbody
    - @prefectures.each do |prefecture|
      %tr
        %td= prefecture.name_ja
        %td= prefecture.name_hira
        %td= prefecture.name_en
        %td= prefecture.latitude
        %td= prefecture.longitude
        %td= prefecture.population
        %td= prefecture.url
        %td= prefecture.twitter
        %td= prefecture.tel
        %td= prefecture.wikipedia
        %td= link_to 'Show', prefecture
        %td= link_to 'Edit', edit_prefecture_path(prefecture)
        %td= link_to 'Destroy', prefecture, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Prefecture', new_prefecture_path

app/views/prefectures/new.html.haml
%h1 New prefecture

= render 'form'

= link_to 'Back', prefectures_path

app/views/prefectures/show.html.haml
%p#notice= notice

%p
  %b Name ja:
  = @prefecture.name_ja
%p
  %b Name hira:
  = @prefecture.name_hira
%p
  %b Name en:
  = @prefecture.name_en
%p
  %b Latitude:
  = @prefecture.latitude
%p
  %b Longitude:
  = @prefecture.longitude
%p
  %b Population:
  = @prefecture.population
%p
  %b Url:
  = @prefecture.url
%p
  %b Twitter:
  = @prefecture.twitter
%p
  %b Tel:
  = @prefecture.tel
%p
  %b Wikipedia:
  = @prefecture.wikipedia

= link_to 'Edit', edit_prefecture_path(@prefecture)
\|
= link_to 'Back', prefectures_path