config/routes.rb
Rails.application.routes.draw do
  resources :prefectures
  resources :cities
  resources :volunteers
  resources :prefectures

  get '/index' , to: 'top#index'
  root to: 'top#index'
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name_ja, :name_hira, :name_en, :city_category_id, :latitude, :longitude, :url, :twitter, :wikipedia, :population)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.haml
= form_for @city do |f|
  - if @city.errors.any?
    #error_explanation
      %h2= "#{pluralize(@city.errors.count, "error")} prohibited this city from being saved:"
      %ul
        - @city.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name_ja
    = f.text_field :name_ja
  .field
    = f.label :name_hira
    = f.text_field :name_hira
  .field
    = f.label :name_en
    = f.text_field :name_en
  .field
    = f.label :city_category_id
    = f.number_field :city_category_id
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :wikipedia
    = f.text_field :wikipedia
  .field
    = f.label :population
    = f.number_field :population
  .actions
    = f.submit 'Save'

app/views/cities/edit.html.haml
%h1 Editing city

= render 'form'

= link_to 'Show', @city
\|
= link_to 'Back', cities_path

app/views/cities/index.html.haml
%h1 Listing cities

%table
  %thead
    %tr
      %th Name ja
      %th Name hira
      %th Name en
      %th City category
      %th Latitude
      %th Longitude
      %th Url
      %th Twitter
      %th Wikipedia
      %th Population
      %th
      %th
      %th

  %tbody
    - @cities.each do |city|
      %tr
        %td= city.name_ja
        %td= city.name_hira
        %td= city.name_en
        %td= city.city_category_id
        %td= city.latitude
        %td= city.longitude
        %td= city.url
        %td= city.twitter
        %td= city.wikipedia
        %td= city.population
        %td= link_to 'Show', city
        %td= link_to 'Edit', edit_city_path(city)
        %td= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New City', new_city_path

app/views/cities/new.html.haml
%h1 New city

= render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.haml
%p#notice= notice

%p
  %b Name ja:
  = @city.name_ja
%p
  %b Name hira:
  = @city.name_hira
%p
  %b Name en:
  = @city.name_en
%p
  %b City category:
  = @city.city_category_id
%p
  %b Latitude:
  = @city.latitude
%p
  %b Longitude:
  = @city.longitude
%p
  %b Url:
  = @city.url
%p
  %b Twitter:
  = @city.twitter
%p
  %b Wikipedia:
  = @city.wikipedia
%p
  %b Population:
  = @city.population

= link_to 'Edit', edit_city_path(@city)
\|
= link_to 'Back', cities_path